// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CovidChart: typeof import('./components/CovidChart.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ReactiveCovidChart: typeof import('./components/ReactiveCovidChart.vue')['default']
  }
}

export { }
