// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CovidChart: typeof import('./components/CovidChart.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FrequentlyAskedQuestions: typeof import('./components/FrequentlyAskedQuestions.vue')['default']
    Operators: typeof import('./components/Operators.vue')['default']
    ReactiveCovidChart: typeof import('./components/ReactiveCovidChart.vue')['default']
    README: typeof import('./components/vue3-good-table/README.md')['default']
    SiteHeader: typeof import('./components/SiteHeader.vue')['default']
    Table: typeof import('./components/vue3-good-table/Table.vue')['default']
    TableComparison: typeof import('./components/TableComparison.vue')['default']
    VgtFilterRow: typeof import('./components/vue3-good-table/VgtFilterRow.vue')['default']
    VgtGlobalSearch: typeof import('./components/vue3-good-table/VgtGlobalSearch.vue')['default']
    VgtHeaderRow: typeof import('./components/vue3-good-table/VgtHeaderRow.vue')['default']
    VgtPagination: typeof import('./components/vue3-good-table/pagination/VgtPagination.vue')['default']
    VgtPaginationPageInfo: typeof import('./components/vue3-good-table/pagination/VgtPaginationPageInfo.vue')['default']
    VgtTableHeader: typeof import('./components/vue3-good-table/VgtTableHeader.vue')['default']
  }
}

export { }
